# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.shared_blueprint_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\SharedBlueprint

    app.shared_blueprint_manager:
        class: AppBundle\Manager\SharedBlueprintManager
        arguments: ['@app.shared_blueprint_repository', '@request_stack']