parameters:

services:
    app.shared_blueprint_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\SharedBlueprint

    app.shared_blueprint_manager:
        class: AppBundle\Manager\SharedBlueprintManager
        arguments: ['@app.shared_blueprint_repository', '@request_stack']